export const ENCODER_DECODER_ADD = "ADD";
export const ENCODER_DECODER_DELETE = "DELETE";
export const ENCODER_DECODER_KEY_MODIFY = "KEY_MODIFY";
export const ENCODER_DECODER_CRUNCH_START = "CRUNCH_START";
export const ENCODER_DECODER_CRUNCH_SUCCESS = "CRUNCH_SUCCESS";
export const ENCODER_DECODER_CRUNCH_ERROR = "CRUNCH_ERROR";